### ISSUE TITLE
Add Wave Array input to node

### ISSUE THREAD

**Issue by Tomavatars** [Cycling74/RNBOMetasound#21]
In order to play audio files living in the unreal project in a RNBO node, I'd like an Wave Array input.
![CleanShot 2023-10-16 at 21 27 46@2x](https://github.com/Cycling74/RNBOMetasound/assets/14031754/1b8ee37b-19f5-4a68-9646-92a1ff28da35)

**Comment by x37v** [comment]
we likely won't be supporting `Wave Asset` anytime soon unfortunately, the current RNBO API just doesn't map well to it, but we should support `Wave Tables`.. so there will be a pair of inputs, one to select a wave table bank and one to select the index within that table

**Comment by x37v** [comment]
this is in develop now
