### ISSUE TITLE
audio io pins could live at the top of the node by default

### ISSUE THREAD

**Issue by jinpavg** [Cycling74/RNBOMetasound#25]
could be slightly more ergonomic for patching in the MS graph

**Comment by x37v** [comment]
@jinpavg what do you think is a good order, we have:

* audio
* float
* bool
* int (to be enum)
* wave asset
* trigger
* midi
* transport

should the order be the same for input and output?

**Comment by jinpavg** [comment]
So -- what if we have a default order, but then also the ability to define pin sort order with `meta` ? The MS graph variables and inputs have this notion of "sort order" where higher numbers are sorted further down the node.

So you could say like

`inport foo @meta sortorder: -1`
`param bar @meta sortorder: 10`

but our default order could prioritize audio input/output, like, this is fairly arbitrary, but maybe:

- audio
- midi
- trigger
- bool
- float
- enum
- wave
- transport

the rationale here being audio could flow across the top of the node, the transport sort of makes sense to patch in at the bottom, the enum and wave dropdowns can be at the bottom so they don't block text when the disclosure menu opens.

**Comment by jinpavg** [comment]
i guess the only thing is you couldn't define sort order on MIDI, Transport, and Wave (since buffer~ doesn't have `@meta`)

**Comment by x37v** [comment]
updated on develop
