### ISSUE TITLE
Develop version is not building on Xcode OSX 13.5.1 : 2 errors

### ISSUE THREAD

**Issue by Tomavatars** [Cycling74/RNBOMetasound#31]
<img width="1074" alt="CleanShot 2023-12-16 at 14 45 34@2x" src="https://github.com/Cycling74/RNBOMetasound/assets/14031754/03c6e65f-18cc-4c29-bdca-165f5885ec43">
<img width="1079" alt="CleanShot 2023-12-16 at 14 45 55@2x" src="https://github.com/Cycling74/RNBOMetasound/assets/14031754/39503cef-a8b2-4bed-9df0-a12c7e1ba21c">

**Comment by x37v** [comment]
hmm, that is interesting, you tried doing a clean then building?

**Comment by x37v** [comment]
I'm building with Xcode 14, I'll see if someone else has 13 to compare

**Comment by Tomavatars** [comment]
> hmm, that is interesting, you tried doing a clean then building?

I deleted everything in RNBO expect my Exports. Deleted the Xcode project. Re generated it. Opened the Xcode project and rebuilt.
I also tried to delete the intermediate and saved folders in the Unreal Project (this sometimes helps)

**Comment by Tomavatars** [comment]
> I'm building with Xcode 14, I'll see if someone else has 13 to compare @jinpavg which version of xcode are you using?
I'm on Xcode 15
![Uploading CleanShot 2023-12-18 at 11.02.53.png…]()

**Comment by Tomavatars** [comment]
> I'm building with Xcode 14, I'll see if someone else has 13 to compare @jinpavg which version of xcode are you using?

I'm on Xcode 15

![CleanShot 2023-12-18 at 11 02 53](https://github.com/Cycling74/RNBOMetasound/assets/14031754/66df789c-f17f-45e0-b2f2-6b92d3dad287)

**Comment by Tomavatars** [comment]
It's still failing to build with 15.1. Here's the dummy project link : [link](https://kdrive.infomaniak.com/app/share/189615/2fc68108-f329-4261-a33b-1c94bbea469d)

**Comment by x37v** [comment]
@Tomavatars I just updated the `develop` branch with a change that resolved the issue for me

**Comment by Tomavatars** [comment]
It works @x37v !!! Thank you so much!
