### ISSUE TITLE
transport "getter" utility node

### ISSUE THREAD

**Issue by jinpavg** [Cycling74/RNBOMetasound#33]
a user could patch this to the Transport node or to the Global Transport node to get data from the active transport:
 
trigger for bar / beat
int for numerator, denominator, bar, beat, position in ticks
float for BPM
bool for state

**Comment by x37v** [comment]
see `feature/transport-util`

**Comment by x37v** [comment]
there is now a `Transport Get` node in `develop`.. it doesn't have the trigger implementations, I think that should be a separate node, but it does get you the entire transport state at block rate

**Comment by x37v** [comment]
@jinpavg this is done right?
